FROM microsoft/dotnet:sdk AS build-env
WORKDIR ../html

# Copy csproj and restore as distinct layers
COPY ../html/./html/*.csproj .csproj ../html
RUN dotnet restore

# Copy everything else and build
COPY . ../html
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR ../html
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "aspnetapp.dll"]



